/*
 * Generated by classgen, version 1.5
 * 11.10.13 11:54
 */
package de.brainiiiii.sqlgen;

public class EnumDekl extends ProjectDeklBlock {

  public String ident;
  public StringList options;

  public EnumDekl (String ident, StringList options) {
    this.ident = ident;
    this.options = options;
    if (options != null) options.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (options != null) options.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (options != null) options.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (options != null) options.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("EnumDekl(\n");
    buffer.append("  "+tab+ident);
    buffer.append("\n");
      if (options != null)
        buffer.append(options.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [EnumDekl]");
    return buffer.toString();
  }
}
