/*
 * Generated by classgen, version 1.5
 * 11.10.13 11:54
 */
package de.brainiiiii.sqlgen;

public class NullableColumnDekl extends ColumnDeklType {

  public NonNullableColumnDekl subType;

  public NullableColumnDekl (NonNullableColumnDekl subType) {
    this.subType = subType;
    if (subType != null) subType.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (subType != null) subType.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (subType != null) subType.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (subType != null) subType.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("NullableColumnDekl(\n");
      if (subType != null)
        buffer.append(subType.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [NullableColumnDekl]");
    return buffer.toString();
  }
}
