/*
 * Generated by classgen, version 1.5
 * 11.10.13 11:54
 */
package de.brainiiiii.sqlgen;

public class SelectDekl extends ProjectDeklBlock {

  public String ident;
  public ColumnDeklList params;
  public SqlSelect stmt;

  public SelectDekl (String ident, ColumnDeklList params, SqlSelect stmt) {
    this.ident = ident;
    this.params = params;
    if (params != null) params.setParent(this);
    this.stmt = stmt;
    if (stmt != null) stmt.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (params != null) params.accept(visitor);
    if (stmt != null) stmt.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (params != null) params.traverseTopDown(visitor);
    if (stmt != null) stmt.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (params != null) params.traverseBottomUp(visitor);
    if (stmt != null) stmt.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("SelectDekl(\n");
    buffer.append("  "+tab+ident);
    buffer.append("\n");
      if (params != null)
        buffer.append(params.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (stmt != null)
        buffer.append(stmt.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [SelectDekl]");
    return buffer.toString();
  }
}
