/*
 * Generated by classgen, version 1.5
 * 11.10.13 11:54
 */
package de.brainiiiii.sqlgen;

public class SingleColumnDekl extends ColumnDekl {

  public String ident;
  public String phyicalName;
  public ColumnDeklType type;
  public DefaultValue defaultValue;

  public SingleColumnDekl (String ident, String phyicalName, ColumnDeklType type, DefaultValue defaultValue) {
    this.ident = ident;
    this.phyicalName = phyicalName;
    this.type = type;
    if (type != null) type.setParent(this);
    this.defaultValue = defaultValue;
    if (defaultValue != null) defaultValue.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (type != null) type.accept(visitor);
    if (defaultValue != null) defaultValue.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (type != null) type.traverseTopDown(visitor);
    if (defaultValue != null) defaultValue.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (type != null) type.traverseBottomUp(visitor);
    if (defaultValue != null) defaultValue.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("SingleColumnDekl(\n");
    buffer.append("  "+tab+ident);
    buffer.append("\n");
    buffer.append("  "+tab+phyicalName);
    buffer.append("\n");
      if (type != null)
        buffer.append(type.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (defaultValue != null)
        buffer.append(defaultValue.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [SingleColumnDekl]");
    return buffer.toString();
  }
}
