/*
 * Generated by classgen, version 1.5
 * 11.10.13 11:54
 */
package de.brainiiiii.sqlgen;

public class SqlColumnExpr extends SqlExpr {

  public String tableName;
  public String columnName;

  public SqlColumnExpr (String tableName, String columnName) {
    this.tableName = tableName;
    this.columnName = columnName;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("SqlColumnExpr(\n");
    buffer.append("  "+tab+tableName);
    buffer.append("\n");
    buffer.append("  "+tab+columnName);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [SqlColumnExpr]");
    return buffer.toString();
  }
}
