/*
 * Generated by classgen, version 1.5
 * 11.10.13 11:54
 */
package de.brainiiiii.sqlgen;

public class SqlOrderElement implements SyntaxNode {

  private SyntaxNode parent;
  public SqlColumnExpr column;
  public boolean ascending;

  public SqlOrderElement (SqlColumnExpr column, boolean ascending) {
    this.column = column;
    if (column != null) column.setParent(this);
    this.ascending = ascending;
  }

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (column != null) column.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (column != null) column.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (column != null) column.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString() {
    return toString("");
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("SqlOrderElement(\n");
      if (column != null)
        buffer.append(column.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append("  "+tab+ascending);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [SqlOrderElement]");
    return buffer.toString();
  }
}
