/*
 * Generated by classgen, version 1.5
 * 11.10.13 11:54
 */
package de.brainiiiii.sqlgen;

public class SqlSpecLimit extends SqlLimit {

  public SqlExpr offset;
  public SqlExpr limit;

  public SqlSpecLimit (SqlExpr offset, SqlExpr limit) {
    this.offset = offset;
    if (offset != null) offset.setParent(this);
    this.limit = limit;
    if (limit != null) limit.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (offset != null) offset.accept(visitor);
    if (limit != null) limit.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (offset != null) offset.traverseTopDown(visitor);
    if (limit != null) limit.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (offset != null) offset.traverseBottomUp(visitor);
    if (limit != null) limit.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("SqlSpecLimit(\n");
      if (offset != null)
        buffer.append(offset.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (limit != null)
        buffer.append(limit.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [SqlSpecLimit]");
    return buffer.toString();
  }
}
