/*
 * Generated by classgen, version 1.5
 * 11.10.13 11:54
 */
package de.brainiiiii.sqlgen;

public class SqlSelectColumn implements SyntaxNode {

  private SyntaxNode parent;
  public SqlExpr expr;
  public String alias;

  public SqlSelectColumn (SqlExpr expr, String alias) {
    this.expr = expr;
    if (expr != null) expr.setParent(this);
    this.alias = alias;
  }

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (expr != null) expr.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (expr != null) expr.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (expr != null) expr.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString() {
    return toString("");
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("SqlSelectColumn(\n");
      if (expr != null)
        buffer.append(expr.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append("  "+tab+alias);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [SqlSelectColumn]");
    return buffer.toString();
  }
}
