/*
 * Generated by classgen, version 1.5
 * 11.10.13 11:54
 */
package de.brainiiiii.sqlgen;

public class SqlSelectSource implements SyntaxNode {

  private SyntaxNode parent;
  public String tableName;
  public String alias;
  public boolean isOptional;

  public SqlSelectSource (String tableName, String alias, boolean isOptional) {
    this.tableName = tableName;
    this.alias = alias;
    this.isOptional = isOptional;
  }

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    accept(visitor);
  }

  public String toString() {
    return toString("");
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("SqlSelectSource(\n");
    buffer.append("  "+tab+tableName);
    buffer.append("\n");
    buffer.append("  "+tab+alias);
    buffer.append("\n");
    buffer.append("  "+tab+isOptional);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [SqlSelectSource]");
    return buffer.toString();
  }
}
