/*
 * Generated by classgen, version 1.5
 * 11.10.13 11:54
 */
package de.brainiiiii.sqlgen;

public class StringType extends NonNullableColumnDekl {

  public int maxLength;

  public StringType (int maxLength) {
    this.maxLength = maxLength;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("StringType(\n");
    buffer.append("  "+tab+maxLength);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [StringType]");
    return buffer.toString();
  }
}
