
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Fri Oct 11 11:54:35 CEST 2013
//----------------------------------------------------

package de.brainiiiii.sqlgen;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int SQL_DESC = 51;
  public static final int CHAR = 23;
  public static final int DATETIME = 27;
  public static final int DOUBLE = 24;
  public static final int TIME = 28;
  public static final int SQL_WHERE = 47;
  public static final int SC = 34;
  public static final int SELECT_DEF = 8;
  public static final int INT = 21;
  public static final int DATE = 26;
  public static final int NULLABLE = 18;
  public static final int ENUM_DEF = 6;
  public static final int STRINGCONST = 44;
  public static final int DATA = 10;
  public static final int DEFINE = 4;
  public static final int SQL_SELECT = 45;
  public static final int INTCONST = 41;
  public static final int TYPE = 5;
  public static final int BOOL = 22;
  public static final int COMMA = 31;
  public static final int REFERENCE = 30;
  public static final int SQL_LIMIT = 49;
  public static final int DOT = 33;
  public static final int ID = 19;
  public static final int EOF = 0;
  public static final int TABLE = 7;
  public static final int error = 1;
  public static final int PROJECT = 3;
  public static final int SQL_FROM = 46;
  public static final int NULL = 17;
  public static final int IDENT = 42;
  public static final int EQ = 32;
  public static final int UNIQUE = 13;
  public static final int INDICES = 9;
  public static final int SQL_ORDER = 48;
  public static final int LBRACE = 35;
  public static final int INDEX = 14;
  public static final int ENUM = 29;
  public static final int PACKAGE = 2;
  public static final int RBRACE = 36;
  public static final int BOOLCONST = 43;
  public static final int OPEN = 37;
  public static final int STRING = 20;
  public static final int SQL_ASC = 50;
  public static final int OLBRACE = 39;
  public static final int TEXT = 25;
  public static final int CLOSE = 38;
  public static final int AS = 12;
  public static final int PRIMARY = 11;
  public static final int AUTO_ID = 16;
  public static final int ORBRACE = 40;
  public static final int FULLTEXT = 15;
}

