/*
 * Generated by classgen, version 1.5
 * 11.10.13 11:54
 */

package de.brainiiiii.sqlgen;

public interface SyntaxNode extends VisitorNode {
  public SyntaxNode getParent();
  public void setParent(SyntaxNode parent);
}
