/*
 * Generated by classgen, version 1.5
 * 11.10.13 11:54
 */
package de.brainiiiii.sqlgen;

public class TableDekl extends ProjectDeklBlock {

  public String ident;
  public String physicalName;
  public ColumnDeklList primaries;
  public ColumnDeklList cols;
  public IndexDeklList indices;

  public TableDekl (String ident, String physicalName, ColumnDeklList primaries, ColumnDeklList cols, IndexDeklList indices) {
    this.ident = ident;
    this.physicalName = physicalName;
    this.primaries = primaries;
    if (primaries != null) primaries.setParent(this);
    this.cols = cols;
    if (cols != null) cols.setParent(this);
    this.indices = indices;
    if (indices != null) indices.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (primaries != null) primaries.accept(visitor);
    if (cols != null) cols.accept(visitor);
    if (indices != null) indices.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (primaries != null) primaries.traverseTopDown(visitor);
    if (cols != null) cols.traverseTopDown(visitor);
    if (indices != null) indices.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (primaries != null) primaries.traverseBottomUp(visitor);
    if (cols != null) cols.traverseBottomUp(visitor);
    if (indices != null) indices.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("TableDekl(\n");
    buffer.append("  "+tab+ident);
    buffer.append("\n");
    buffer.append("  "+tab+physicalName);
    buffer.append("\n");
      if (primaries != null)
        buffer.append(primaries.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (cols != null)
        buffer.append(cols.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (indices != null)
        buffer.append(indices.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [TableDekl]");
    return buffer.toString();
  }
}
