/*
 * Generated by classgen, version 1.5
 * 11.10.13 11:54
 */
package de.brainiiiii.sqlgen;

public interface Visitor {

  public void visit(ProjectDeklBlockList projectDeklBlockList);
  public void visit(StringList stringList);
  public void visit(ColumnDeklList columnDeklList);
  public void visit(IndexDeklList indexDeklList);
  public void visit(SqlSelectColumnList sqlSelectColumnList);
  public void visit(SqlSelectSourceList sqlSelectSourceList);
  public void visit(SqlOrderElementList sqlOrderElementList);
  public void visit(Project project);
  public void visit(IndexDekl indexDekl);
  public void visit(SqlSelectSource sqlSelectSource);
  public void visit(SqlSelectColumn sqlSelectColumn);
  public void visit(SqlOrderElement sqlOrderElement);
  public void visit(SqlSelect sqlSelect);
  public void visit(PackageDekl packageDekl);
  public void visit(PackageDekl0 packageDekl0);
  public void visit(PackageDekl1 packageDekl1);
  public void visit(ProjectDeklBlock projectDeklBlock);
  public void visit(EnumDekl enumDekl);
  public void visit(TableDekl tableDekl);
  public void visit(SelectDekl selectDekl);
  public void visit(ColumnDekl columnDekl);
  public void visit(SingleColumnDekl singleColumnDekl);
  public void visit(ArrayColumnDekl arrayColumnDekl);
  public void visit(DefaultValue defaultValue);
  public void visit(DefaultAuto defaultAuto);
  public void visit(DefaultConstNull defaultConstNull);
  public void visit(DefaultConstInt defaultConstInt);
  public void visit(DefaultConstString defaultConstString);
  public void visit(DefaultConstBool defaultConstBool);
  public void visit(ColumnDeklType columnDeklType);
  public void visit(NullableColumnDekl nullableColumnDekl);
  public void visit(NonNullableColumnDekl nonNullableColumnDekl);
  public void visit(IDType iDType);
  public void visit(StringType stringType);
  public void visit(IntType intType);
  public void visit(BooleanType booleanType);
  public void visit(CharType charType);
  public void visit(DoubleType doubleType);
  public void visit(TextType textType);
  public void visit(DateType dateType);
  public void visit(DateTimeType dateTimeType);
  public void visit(TimeType timeType);
  public void visit(EnumType enumType);
  public void visit(TableReferenceType tableReferenceType);
  public void visit(ColumnReferenceType columnReferenceType);
  public void visit(SqlExpr sqlExpr);
  public void visit(SqlColumnExpr sqlColumnExpr);
  public void visit(SqlConstStringExpr sqlConstStringExpr);
  public void visit(SqlParamExpr sqlParamExpr);
  public void visit(SqlNullExpr sqlNullExpr);
  public void visit(SqlConstBoolExpr sqlConstBoolExpr);
  public void visit(SqlLimit sqlLimit);
  public void visit(SqlSpecLimit sqlSpecLimit);
  public void visit(SqlNoLimit sqlNoLimit);

}
