/*
 * Generated by classgen, version 1.5
 * 11.10.13 11:54
 */

package de.brainiiiii.sqlgen;

public interface VisitorNode {
  public void accept(Visitor visitor);

  public void childrenAccept(Visitor visitor);
  public void traverseBottomUp(Visitor visitor);
  public void traverseTopDown(Visitor visitor);
}
